### Task 1: Data Profiling and Missing Values (~25 minutes)
**1.1** — Profile the raw data
Compute a comprehensive profile of the dataset:

Number of rows, columns, and memory usage
Missing value counts and percentages for each column
Number of unique values per column
Basic statistics for numeric columns (min, max, mean, median, std)

**1.2** — Classify the missing data types
The two columns with significant missing values are CustomerID and Description.

For each:

Determine whether the missingness is MNAR, MAR, or MCAR. Justify your answer with evidence (e.g., compare rows with and without missing values — do they differ systematically in other columns?).
Decide on a strategy: deletion, imputation, or indicator column. Justify your choice.
Guiding questions:

Are transactions with missing CustomerID different from those with a CustomerID? Check the distribution of Country, Quantity, and UnitPrice for both groups.
Do transactions with missing Description have valid StockCode values? Could you recover descriptions from other rows with the same StockCode?

**1.3** — Handle the missing values
Apply your chosen strategies. Document what you did and why. After handling missing values, print the remaining missing value counts to confirm.

Deliverable for Task 1
A profiling summary, a written classification of missing data types with evidence, and clean handling with documentation.

In [102]:
import pandas as pd
import numpy as np

df = pd.read_excel("C:\\Users\\Asus\\Downloads\\Online Retail.xlsx")

In [103]:
print (f"Shape: {df.shape}")
print("\nColumn types:\n",df.dtypes)

Shape: (541909, 8)

Column types:
 InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [104]:
missing=df.isnull().sum()
missing_percent=(missing/len(df))*100
print("\nMissing values (count and %):\n" , pd.DataFrame({"count" : missing , "percent" : missing_percent }))

Missing values (count and %):
               count    percent
InvoiceNo         0   0.000000
StockCode         0   0.000000
Description    1454   0.268311
Quantity          0   0.000000
InvoiceDate       0   0.000000
UnitPrice         0   0.000000
CustomerID   135080  24.926694
Country           0   0.000000

In [105]:
unique_counts = df.nunique()
print("\nUnique values per column:\n", unique_counts)

print("\nNumeric column statistics:\n", df.describe())

Unique values per column:
 InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

Numeric column statistics:
             Quantity                    InvoiceDate      UnitPrice  \
count  541909.000000                         541909  541909.000000
mean        9.552250  2011-07-04 13:34:57.156386048       4.611114
min    -80995.000000            2010-12-01 08:26:00  -11062.060000
25%         1.000000            2011-03-28 11:34:00       1.250000
50%         3.000000            2011-07-19 17:17:00       2.080000
75%        10.000000            2011-10-19 11:27:00       4.130000
max     80995.000000            2011-12-09 12:50:00   38970.000000
std       218.081158                            NaN      96.759853

          CustomerID
count  406829.000000
mean    15287.690570
min     12346.000000
25%     13953.000000
50%     15152.000000
75%     16791.000000
max     18287.000000
std      1713.600303

In [106]:
print(f"\nFirst rows:\n ,{df.head()}")

First rows:
 ,  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

**1.2** — Classify the missing data types The two columns with significant missing values are CustomerID and Description.

For each:

Determine whether the missingness is MNAR, MAR, or MCAR. Justify your answer with evidence (e.g., compare rows with and without missing values — do they differ systematically in other columns?). Decide on a strategy: deletion, imputation, or indicator column. Justify your choice. Guiding questions:

Are transactions with missing CustomerID different from those with a CustomerID? Check the distribution of Country, Quantity, and UnitPrice for both groups. Do transactions with missing Description have valid StockCode values? Could you recover descriptions from other rows with the same StockCode?

In [107]:
missing_customer= df[df["CustomerID"].isnull()]
non_missing_customer=df[df["CustomerID"].notnull()]
missing_customer.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom

In [108]:
# Compare distributions
print(missing_customer['Country'].value_counts())
print(non_missing_customer['Country'].value_counts())
print(missing_customer['Quantity'].describe())
print(non_missing_customer['Quantity'].describe())
print(missing_customer['UnitPrice'].describe())
print(non_missing_customer['UnitPrice'].describe())

Country
United Kingdom    133600
EIRE                 711
Hong Kong            288
Unspecified          202
Switzerland          125
France                66
Israel                47
Portugal              39
Bahrain                2
Name: count, dtype: int64
Country
United Kingdom          361878
Germany                   9495
France                    8491
EIRE                      7485
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               1877
Portugal                  1480
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
USA                        291
Israel                     250
Unspecified                244
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     17
Saudi Arabia                10
Name: count, dtype: int64
count    135080.000000
mean          1.995573
std          66.696153
min       -9600.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        5568.000000
Name: Quantity, dtype: float64
count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64
count    135080.000000
mean          8.076577
std         151.900816
min      -11062.060000
25%           1.630000
50%           3.290000
75%           5.450000
max       17836.460000
Name: UnitPrice, dtype: float64
count    406829.000000
mean          3.460471
std          69.315162
min           0.000000
25%           1.250000
50%           1.950000
75%           3.750000
max       38970.000000
Name: UnitPrice, dtype: float64

In [109]:
print("Quantity stats:")
print("Missing CustomerID:\n", missing_cust['Quantity'].describe())
print("-"*30)
print("Has CustomerID:\n", has_cust['Quantity'].describe())

Quantity stats:
Missing CustomerID:
 count    135080.000000
mean          1.995573
std          66.696153
min       -9600.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        5568.000000
Name: Quantity, dtype: float64
------------------------------
Has CustomerID:
 count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [110]:
print("\nCountry distribution for missing CustomerID:\n", missing_cust['Country'].value_counts())

Country distribution for missing CustomerID:
 Country
United Kingdom    133600
EIRE                 711
Hong Kong            288
Unspecified          202
Switzerland          125
France                66
Israel                47
Portugal              39
Bahrain                2
Name: count, dtype: int64

In [111]:
missing_desc=df[df["Description"].isnull()]
missing_desc

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
535326,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
535332,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [112]:
#stockcodelari olanlari eyni olanlari descriotionu evez et
#delete unit price

**1.2**
Observations

- Most rows with missing CustomerID are one-off purchases or “guest” transactions.

- Distribution of Quantity and UnitPrice is similar between missing and non-missing CustomerID rows.

- There are systematic differences in Country: many missing CustomerID rows come from non-UK countries.

Missingness Type

- Missingness depends on other observed variables (Country), not the missing CustomerID itself.

Therefore, this is MAR (Missing at Random).

Handling Strategy

Since CustomerID is critical for customer-level analysis, we cannot reliably impute missing values.

Decision: Remove rows with missing CustomerID when performing customer-level aggregation.

For transaction-level analysis, rows can be retained if needed but flagged as “anonymous” customers.

**Observations**

Missing descriptions mostly correspond to valid StockCodes, often non-product codes like POST, D, or discounts.

Some missing descriptions can be recovered by looking up the most common description for the same StockCode.

Missingness is related to StockCode, not the description itself.

Missingness Type

Since missingness depends on another observed column (StockCode), this is also MAR (Missing at Random).

Handling Strategy

Impute missing descriptions using the most frequent description per StockCode.

Non-product codes can be flagged or left as-is.

In [113]:
df["Description"]=df.groupby("StockCode")["Description"].transform( lambda x : x.fillna(x.mode()[0] if not x.mode().empty else "Unknown"))

In [114]:
#1.3
invalid_prices=df[df["UnitPrice"]<=0]
print("Count of invalid prices: ",len(invalid_prices))

Count of invalid prices:  2517

In [115]:
df = df[(df['CustomerID'].notnull()) & (df['UnitPrice'] > 0)]

In [116]:
print(f"after cleaning: {df.shape}")
print(f"CustomerID NaN : {df['CustomerID'].isnull().sum()}")
print(f"UnitPrice <= 0 : {(df['UnitPrice'] <= 0).sum()}")

after cleaning: (406789, 8)
CustomerID NaN : 0
UnitPrice <= 0 : 0

## Task 1.3 — Handle Invalid Quantities and Prices

In the dataset, we identified three types of invalid or anomalous records:

1. **Missing CustomerID**  
   - Rows with `CustomerID = NaN` usually correspond to one-off or guest transactions.  
   - Since `CustomerID` is critical for customer-level analysis, and the number of missing rows does not significantly affect dataset size, we decided to **remove these rows**.

2. **Invalid UnitPrice**  
   - Some transactions have `UnitPrice <= 0`, which is invalid for product sales.  
   - These may correspond to errors or returns, so we decided to **remove these rows**.

3. **Invalid Quantity**  
   - Some transactions have `Quantity <= 0` (excluding cancellations that start with "C").  
   - These are not meaningful for revenue analysis and should also be removed.

After applying these cleaning rules, the dataset will only contain **valid transactions with positive quantities and prices, and valid customer IDs**.

### Task 2: Cleaning Invalid and Anomalous Records

**2.1** — Identify cancellations
Invoices starting with "C" are cancellations. These have negative quantities and represent returns, not purchases.

Count how many cancellation transactions exist.
Decide whether to keep, remove, or flag them. Think about the downstream task: if you later want to predict customer churn or build a recommender, how do cancellations affect the analysis?

In [117]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [118]:
df["IsCancellation"] = df["InvoiceNo"].str.startswith("C", na=False)

In [119]:
df["IsCancellation"].sum()

np.int64(8905)

In [120]:
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_clean.shape}")

Original DataFrame shape: (406789, 9)
Cleaned DataFrame shape: (397884, 14)

In [123]:
df_clean['IsCancellation'] = df_clean['IsCancellation'].astype(bool)
print(f"Missing CustomerID: {df_clean['CustomerID'].isnull().sum()}")
print(f"UnitPrice <= 0: {(df_clean['UnitPrice'] <= 0).sum()}")
print(f"Quantity <= 0 (non-cancellations): {((df_clean['Quantity'] <= 0) & (~df_clean['IsCancellation'])).sum()}")

Missing CustomerID: 0
UnitPrice <= 0: 0
Quantity <= 0 (non-cancellations): 0

In [124]:
import pandas as pd

df["isCancellation"] = df["InvoiceNo"].str.startswith("C", na=False)

df_clean = df[~df["isCancellation"]].copy()

df_clean['isCancellation'] = df_clean['isCancellation'].astype(bool)



neg_qty_count = (df_clean['Quantity'] <= 0).sum()

neg_unitprice_count = (df_clean['UnitPrice'] <= 0).sum()

missing_customer_count = df_clean['CustomerID'].isnull().sum()

print(f"Original dataset sətir sayı: {df.shape[0]}")
print(f"Cleaned dataset sətir sayı: {df_clean.shape[0]}")
print(f"Quantity <= 0 (non-cancellations): {neg_qty_count}")
print(f"UnitPrice <= 0: {neg_unitprice_count}")
print(f"Missing CustomerID: {missing_customer_count}")

df_clean.head(10)

Original dataset sətir sayı: 406789
Cleaned dataset sətir sayı: 397884
Quantity <= 0 (non-cancellations): 0
UnitPrice <= 0: 0
Missing CustomerID: 0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsCancellation,isCancellation
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,False,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,False,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False,False
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,False,False
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,False,False
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,False,False
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,False,False
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,False,False

### Task 3: Categorical Data Challenges
**3.1** — Analyze the Country column
How many unique countries are there?
What percentage of transactions come from the top 5 countries?
How many countries have fewer than 50 transactions?
Create a cleaned version of the Country column that groups rare countries (fewer than 50 transactions) into an "Other" category. Compare the number of categories before and after.

**3.2** — Analyze the StockCode column
StockCode is a high-cardinality categorical feature.

How many unique stock codes exist?
Are there non-product codes (e.g., postage, discounts, manual adjustments)? Identify them by looking at codes that are not purely numeric or have unusual patterns.
Decide how to handle non-product codes for a product-level analysis.

**3.3** — Engineer a feature from Description
The Description column contains free text. Create a simple feature from it — for example, the word count of the description, or a flag for descriptions containing certain keywords (e.g., "SET", "PACK", "VINTAGE"). Show that your engineered feature has a meaningful relationship with Quantity or UnitPrice.

In [125]:
#3.1
country_counts=df["Country"].value_counts()
print("Number of unique countries:", df_clean['Country'].nunique())
print("Top 5 countries by transaction count:\n", country_counts.head())
print("Countries with fewer than 50 transactions:", (country_counts < 50).sum())

Number of unique countries: 37
Top 5 countries by transaction count:
 Country
United Kingdom    361854
Germany             9493
France              8490
EIRE                7483
Spain               2532
Name: count, dtype: int64
Countries with fewer than 50 transactions: 6

In [126]:
df_clean["Country_clean"]=df_clean["Country"].apply( lambda x : x if country_counts[x] >50 else "Other") 
print("Number of categories after grouping rare countries:", df_clean['Country_clean'].nunique())

Number of categories after grouping rare countries: 32

In [127]:
#3.2
stock_counts = df_clean['StockCode'].value_counts()
print("Number of unique StockCodes:", df_clean['StockCode'].nunique())

Number of unique StockCodes: 3665

In [128]:
non_product_codes = df_clean[~df_clean['StockCode'].astype(str).str.isnumeric()]['StockCode'].unique()
print("Non-product StockCodes examples:", non_product_codes[:10])

Non-product StockCodes examples: ['85123A' '84406B' '84029G' '84029E' 'POST' '82494L' '85099C' '84997B'
 '84997C' '84519A']

In [129]:
df_clean['IsProduct'] = df_clean['StockCode'].notnull() & df_clean['StockCode'].astype(str).str.isnumeric()

In [130]:
# 3.3 Engineer a feature from Description
# Word count
df_clean['Description_WordCount'] = df_clean['Description'].apply(lambda x: len(str(x).split()))

keywords = ['SET', 'PACK', 'VINTAGE']
df_clean['Description_KeywordFlag'] = df_clean['Description'].apply(
    lambda x: int(any(k in str(x).upper() for k in keywords))
)

print(df_clean.groupby('Description_KeywordFlag')[['Quantity', 'UnitPrice']].mean())

                          Quantity  UnitPrice
Description_KeywordFlag
0                        13.044098   3.196337
1                        12.774299   2.810672

### Task 4: Class Imbalance — Predicting High-Value Customers

**4.1** — Engineer a binary target
Create a customer-level dataset by aggregating transactions per CustomerID. Compute:

Total revenue (Quantity * UnitPrice)

Number of orders (unique InvoiceNo values)

Number of distinct products purchased

Date of first and last purchase

Define a binary target: a customer is high-value if their total revenue is in the top 10%. Label these as 1 and the rest as 0.

In [131]:
#4.1
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.utils import resample

In [132]:
customer_df= df_clean.groupby("CustomerID").agg(
    total_revenue=('Quantity', lambda x: (x * df_clean.loc[x.index, 'UnitPrice']).sum()),
    num_orders=("InvoiceNo","nunique"),
    num_products=("StockCode","nunique"),
    first_purchase=("InvoiceDate","min"),
    last_purchase=("InvoiceDate","max")
).reset_index()

In [133]:
threshold=customer_df['total_revenue'].quantile(0.9)

In [134]:
customer_df["high_value"]=(customer_df["total_revenue"]>=threshold).astype(int)

In [135]:
#4.2
print("Class distribution (proportion):")
print(customer_df['high_value'].value_counts(normalize=True))

Class distribution (proportion):
high_value
0    0.899954
1    0.100046
Name: proportion, dtype: float64

In [136]:
majority_accuracy = (customer_df['high_value'] == 0).mean()
print(f"Accuracy if always predict majority class (0): {majority_accuracy:.2f}")

Accuracy if always predict majority class (0): 0.90

In [137]:
print("\nObservation:")
print("- Dataset is imbalanced: minority class (high-value) is much smaller.")
print("- Accuracy is misleading because a model can predict majority class all the time and still get high accuracy.")
print("- Use precision, recall, and F1-score for proper evaluation.")

Observation:
- Dataset is imbalanced: minority class (high-value) is much smaller.
- Accuracy is misleading because a model can predict majority class all the time and still get high accuracy.
- Use precision, recall, and F1-score for proper evaluation.

In [138]:
#4.3
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.utils import resample

In [139]:
features = ['total_revenue', 'num_orders', 'num_products']
X = customer_df[features]
y = customer_df['high_value']

In [140]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [141]:
train_data = X_train.copy()
train_data['high_value'] = y_train

In [142]:
oversampled_minority = resample(
    train_data[train_data['high_value']==1],
    replace=True,
    n_samples=train_data[train_data['high_value']==0].shape[0],  # balance with majority
    random_state=42
)
train_oversample = pd.concat([train_data[train_data['high_value']==0], oversampled_minority])

In [143]:
undersampled_majority = resample(
    train_data[train_data['high_value']==0],
    replace=False,
    n_samples=train_data[train_data['high_value']==1].shape[0],  # balance with minority
    random_state=42
)
train_undersample = pd.concat([train_data[train_data['high_value']==1], undersampled_majority])

In [144]:
def train_eval(X_train, y_train, X_test, y_test, model=LogisticRegression(max_iter=1000)):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred, target_names=['Regular','High-Value']))

In [145]:
print("Original train set:")
train_eval(X_train, y_train, X_test, y_test)

print("Oversampled train set:")
train_eval(train_oversample[features], train_oversample['high_value'], X_test, y_test)

print("Undersampled train set:")
train_eval(train_undersample[features], train_undersample['high_value'], X_test, y_test)

Original train set:
              precision    recall  f1-score   support

     Regular       1.00      1.00      1.00       781
  High-Value       1.00      1.00      1.00        87

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

Oversampled train set:
              precision    recall  f1-score   support

     Regular       1.00      1.00      1.00       781
  High-Value       1.00      1.00      1.00        87

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

Undersampled train set:
              precision    recall  f1-score   support

     Regular       1.00      1.00      1.00       781
  High-Value       0.99      1.00      0.99        87

    accuracy                           1.00       868
   macro avg       0.99      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

### Task 5: Data Leakage — Introduce, Detect, and Fix
**5.1** — Intentionally introduce temporal leakage
The dataset spans December 2010 through December 2011. Suppose you want to predict whether a customer will make a purchase in December 2011 based on their behavior in earlier months.

First, do it wrong: randomly split all customer features (computed from the full date range) into train and test sets. Train a model and record its performance.

In [147]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

features = ['total_revenue', 'num_orders', 'num_products']
X = customer_df[features]
y = customer_df['high_value'] 

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Performance with temporal leakage (do it wrong):")
print(classification_report(y_test, y_pred, target_names=['Regular', 'High-Value']))

Performance with temporal leakage (do it wrong):
              precision    recall  f1-score   support

     Regular       1.00      1.00      1.00       781
  High-Value       1.00      1.00      1.00        87

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

In [148]:
#5.2
# 1️⃣ Check if features include future data
print("Feature columns summary (check for future information):")
print(customer_df[['total_revenue','num_orders','num_products']].describe())

# 2️⃣ Check correlation between features and target
corr = customer_df[['total_revenue','num_orders','num_products','high_value']].corr()
print("\nCorrelation with target:")
print(corr['high_value'].sort_values(ascending=False))

# 3️⃣ Check suspiciously high performance
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

features = ['total_revenue','num_orders','num_products']
X = customer_df[features]
y = customer_df['high_value']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\nModel performance (with leakage):")
print(classification_report(y_test, y_pred, target_names=['Regular','High-Value']))

Feature columns summary (check for future information):
       total_revenue   num_orders  num_products
count    4338.000000  4338.000000   4338.000000
mean     2054.266460     4.272015     61.501153
std      8989.230441     7.697998     85.366768
min         3.750000     1.000000      1.000000
25%       307.415000     1.000000     16.000000
50%       674.485000     2.000000     35.000000
75%      1661.740000     5.000000     77.000000
max    280206.020000   209.000000   1787.000000

Correlation with target:
high_value       1.000000
num_orders       0.533976
num_products     0.458322
total_revenue    0.391280
Name: high_value, dtype: float64

Model performance (with leakage):
              precision    recall  f1-score   support

     Regular       1.00      1.00      1.00       781
  High-Value       1.00      1.00      1.00        87

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

In [149]:
#5.3
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Temporal split
observation_end = pd.Timestamp("2011-09-30")
prediction_start = pd.Timestamp("2011-10-01")

# Observation window (features)
df_obs = df_clean[df_clean['InvoiceDate'] <= observation_end]

# Prediction window (target)
df_pred = df_clean[df_clean['InvoiceDate'] >= prediction_start]

# ------------------------
# Create customer-level features from observation window
customer_features = df_obs.groupby('CustomerID').agg(
    total_revenue=('Quantity', lambda x: (x * df_obs.loc[x.index, 'UnitPrice']).sum()),
    num_orders=('InvoiceNo', 'nunique'),
    num_products=('StockCode', 'nunique')
).reset_index()

# ------------------------
# Create target from prediction window
customer_target = df_pred.groupby('CustomerID').agg(
    purchase_in_pred=('InvoiceNo', lambda x: 1 if x.nunique() > 0 else 0)
).reset_index()

# Merge features and target
customer_df_temporal = pd.merge(customer_features, customer_target, on='CustomerID', how='left')
customer_df_temporal['purchase_in_pred'] = customer_df_temporal['purchase_in_pred'].fillna(0)

# ------------------------
# Train/test split
features = ['total_revenue','num_orders','num_products']
X = customer_df_temporal[features]
y = customer_df_temporal['purchase_in_pred']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ------------------------
# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# ------------------------
# Evaluate
print("Model performance (correct temporal split):")
print(classification_report(y_test, y_pred, target_names=['No Purchase','Purchase']))

Model performance (correct temporal split):
              precision    recall  f1-score   support

 No Purchase       0.66      0.80      0.72       354
    Purchase       0.76      0.61      0.67       367

    accuracy                           0.70       721
   macro avg       0.71      0.70      0.70       721
weighted avg       0.71      0.70      0.70       721